### ISSUE TITLE
Incorrect highlighting of literal:`\``

### ISSUE THREAD

**Issue by Benjamin-Lee** [siko1056/language-sphinx#3]
The string

    literal:`\``

Should be an escaped backtick but instead highlights the entire area following it.

**Comment by siko1056** [comment]
Thank you for the bug report.  Are you referring to the [literal](http://docutils.sourceforge.net/docs/ref/rst/roles.html#literal) feature?  In this case, your example rather should be

    :literal:`\``

which produces "more correct" highlighting.  Otherwise can you give me a hint what you expect (maybe a larger portion of your documentation)?

**Comment by Benjamin-Lee** [comment]
Sorry, that was a typo on my part. It is 

    :literal:`\``


Here's an example of the incorrect highlighting:
![pic](https://snag.gy/h2DA5J.jpg)

**Comment by siko1056** [comment]
Finally I found time to hopefully resolve your issue by 2a7c098. This will be part of the next update v0.1.8 coming soon this day.  Would you give it a try @Benjamin-Lee  and provide some feedback?

**Comment by Benjamin-Lee** [comment]
Fixed it! Thanks!!
